### ISSUE TITLE
purpose of MMEXVERSION in INFOTABLE_V1

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/database#26]
```
> select MMEXVERSION from INFOTABLE_V1;
1.4.0-Alpha.4
```

I think it means *database file created with this version*. After changing value to random text it's not overwritten nor used/validated...

Should we change this to CREATED_WITH?
What about upgraded db files? Should we add LAST_SAVED_WITH?

**Comment by gabriele-v** [comment]
I agree that It's more useful to have the LAST_SAVED_WITH, but when update that field? On MMEX exit?
