### ISSUE TITLE
Generate diagramm for readme.md

### ISSUE THREAD

**Issue by scilganon** [moneymanagerex/database#36]
what about using this tool to generate img on each release

http://www.schemacrawler.com/diagramming.html

---

is it possible to add detailed description for schema? could be useful for developers, who wants to
* push some data directly 
* read some values

**Comment by slodki** [comment]
I'm working on this. SchemaCrawler is fixed now (schemacrawler/SchemaCrawler#216) to generate nice diagrams for SQLite. But it will produce output similar to already existing tables.sql file. #23 must be implemented for auto-generating UML diagrams for MMEX databases.

WIP: [tables.pdf](https://github.com/moneymanagerex/database/files/2612246/tables.pdf)
