### ISSUE TITLE
Database user version

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/database#4]
What is the current user version of the database schema?
Should we store upgrade scripts separately? Some users are not using the desktop version and I would need to upgrade their schema but I am not sure how to identify the schema versions. Some tables, like stock history, are missing.
Also, I would like to add a table for Asset Allocation and would like it to be synchronised with the desktop version of the application. What is the best way to do this?
Thanks for any tips.

**Comment by guanlisheng** [comment]
hey, we determine the database version via a entry in table INFOTABLE_V1.INFONAME = 'DATAVERSION'

https://github.com/moneymanagerex/moneymanagerex/blob/3d9aeed1cc7d541a553a0b76f503a18593700f1e/src/model/Model_Infotable.cpp

**Comment by MisterY** [comment]
Hi, thanks! Great, that's what I thought. On Android, in SQLite helper class, there is a method OnUpgrade which gets this value automatically. The actual value is stored in Pragmas as UserVersion. 
I'm interested whether you are using this value anywhere?

I find it convenient to place the upgrade/migration scripts there, as the db engine takes care of the rest.
What I'm wondering is if I should have a parallel mechanism for upgrading of the db schema for the users who are not using the desktop version. Some users also do not upgrade regularly and are sometimes missing the new tables. So I'm just thinking out loud.

That ties to another suggestion - to store the migration scripts (.sql) from version to version. I have not (yet) looked at the source to confirm how it is done currently.

**Comment by guanlisheng** [comment]
There is no migration scripts/sql yet and we have latest version in one file. that's why we don't like to change the database by modification existing tables.  we are ok to add some new tables

**Comment by MisterY** [comment]
Yes, exactly, that's what I just figured out. I've updated the above post instead of creating new one. Please have a second look.

**Comment by guanlisheng** [comment]
great. 
BTW, the DAU of the desktop version is around 4k. how about the android version?

**Comment by MisterY** [comment]
It's actually inside the Android system so no additional load on the app.
But that sometimes creates a problem because I can't influence the SQLite version on a particular system.
There are some strange cases where the same database file works fine on one platform (i.e. Windows) but does not show any data on other (Android, certain versions). For example, I keep this one open to collect more info: https://github.com/moneymanagerex/android-money-manager-ex/issues/517

**Comment by slodki** [comment]
Should this issue be closed?

**Comment by gabriele-v** [comment]
Yes, I close the issue.
