### ISSUE TITLE
Update for MMEX v1.8.0

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/database#54]
Please can this project be updated to the [v1.8.0](https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.8.0) database structure.

**Comment by n-stein** [comment]
I'm not sure what you mean. This project defines the database of moneymanagerex -- the MMEX database headers are built off of this repo as a submodule, it is not possible for it to lag the version used in MMEX releases.

Does something appear to be old/missing?

**Comment by luisdev** [comment]
Sory, n-stein. I wasn't looking at it properly while trying to write a change/fix for web-money-manager-ex and I got the impression that tables.png was out of date.

Thanks for the explanation.

**Comment by n-stein** [comment]
> I got the impression that tables.png was out of date.

Ah, while it is not possible for tables.sql to lag the database in MMEX, it _is_ possible that tables.png can be out of date. In fact it was outdated for roughly 4 months following the release of 1.7.0, but was brought current with #53 a month ago.
