### ISSUE TITLE
Set up the upgrade procedure to use migrations (version files)

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/database#7]
As we mentioned this topic separately and inside other issues, I'd open a separate issue here.

On Android, in SQLite helper class, there is a method OnUpgrade which gets the database version value automatically. The actual value is stored in Pragmas as User_Version ([ref](https://www.sqlite.org/pragma.html#pragma_schema_version)).

I find it convenient to place the upgrade/migration scripts inside this onUpgrade method, as the db engine takes care of the rest (version upgrade, execution of the scripts).

The suggestion is to modify the current process to store the migration scripts (.sql) from version to version, as separate files that can be executed in sequence, instead of having everything in one create_db script.

This way we would get the ability to migrate any data between versions as well as modifications to existing tables.
If we decide to store file-per-version scripts, then you might apply the same logic and execute all **"database_version_" + versionNumber + ".sql"** scripts to catch up. I believe this would work well for all the platforms and would make the migrations easier in the future.

The change is not significantly different but would allow Android app to upgrade the schema for the users who have old versions or no desktop application at all.
I'm getting exceptions from users on Linux who are missing tables, for example.

**Comment by guanlisheng** [comment]
@moneymanagerex/desktop-mmex-team

**Comment by guanlisheng** [comment]
sorry for the delay while i don't have clear idea how to achieve this. @MisterY

**Comment by MisterY** [comment]
Sure, no problem. Perhaps it is best to illustrate the above concept in some real-world examples. If anything is not clear, just let me know and I'll try to explain in more detail.
Below are some examples of the implementation. 

### Current Situation

We have files 
- database_v1.sql
- database_v2.sql

### New database creation

When creating a new .db file, the generation SQL scripts are executed in order. First, the database_v1.sql is run. This is the current script that generates the initial version of the database. Then database_v2.sql. This file is here just as an example. In reality it can contain any changes for the v2 of the database. These changes will be shown in further scenarios.

Running both scripts will end up in the latest version of the database, including schema *and* data.

### Adding changes to the database

Let's say that we want to add the new Notes field to the Splits table. We will create **database_v3.sql** file with the command (for example)

    ALTER TABLE Splits CREATE NEW COLUMN Notes TEXT NULL

Now we will end up with 
- database_v1.sql
- database_v2.sql
- database_v3.sql

When run sequentially, the end result will be the database version 3 with the Notes field in Splits table and everything else before that.

### Upgrade of the database

Upgrading the existing databases would happen by reading the current database version and then running any missing version files until the latest one.
The database version is read from the **User_Version** field in the .db file.
For example, the database opened is version 1. The application will then execute 
- database_v2.sql, and
- database_v3.sql
in order to bring it up-to-date.

The latest version number is stored in the application itself so that it can always update earlier databases to the version required to work with it.

**Comment by MisterY** [comment]
An important issue that came up in discussion relates do downgrading or, even worse, emergency downgrading in case of problems with the new version.
To cover this case, the upgrade process should always create a backup copy of the original database file (to "filename_v(N-1)" with either .mmb or .bak extension). This would allow manual restore of the database and downgrade of the application version.
Besides the idea that a backup is a good option before upgrade in any case.

**Comment by gabriele-v** [comment]
@guanlisheng I think we can close this because we have take the decision here.
